name: Manual Project Run

on:
  workflow_dispatch:
    # Optional: You can define inputs that prompt the user when they click run
    inputs:
      environment:
        description: 'Environment to run against'
        type: choice
        required: true
        default: 'dev'
        options:
          - dev
          - staging
        

jobs:
  run-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Announce environment
        run: echo "Starting project in ${{ github.event.inputs.environment }} mode..."

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci

      - run: npx playwright install --with-deps

      - run: npx playwright test